# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"9\n\x13\x41uthenticateRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"3\n\x14\x41uthenticateResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t2U\n\x0c\x41uthenticate\x12\x45\n\x0c\x61uthenticate\x12\x19.auth.AuthenticateRequest\x1a\x1a.auth.AuthenticateResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATEREQUEST._serialized_start=20
  _AUTHENTICATEREQUEST._serialized_end=77
  _AUTHENTICATERESPONSE._serialized_start=79
  _AUTHENTICATERESPONSE._serialized_end=130
  _AUTHENTICATE._serialized_start=132
  _AUTHENTICATE._serialized_end=217
# @@protoc_insertion_point(module_scope)
